### ISSUE TITLE
Pi-hole Embedded in Iframe via SSL Fails (X-Frame-Options: SAMEORIGIN)

### ISSUE THREAD

**Issue by trippmartin** [hassio-addons/addon-pi-hole#10]
# Problem/Motivation

I'm trying to embed the Pi-hole add-on as an iframe in Hassio. I am receiving the following browser exception and the iframe does not render:
Refused to display 'https://SERVER:PORT/admin/index.php' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

The Hassio interface is running on one port and the Pi-hole admin interface is running on a different port. Both are configured for HTTPS.

## Expected behavior

I would expect the iframe to render. I imagine we need the ability to disable the X-Frame-Options HTTP header in the Pi-hole instance running in the container.

I found this:
https://www.reddit.com/r/pihole/comments/4o96dd/updated_to_v27_dont_see_the_new_admin_pages_in/

Looks like in pi-hole/rootfs/etc/nginx/nginx-ssl.conf, the following line sets the header. I'm going to see if I can figure out how tie this to a configuration setting.
`add_header X-Frame-Options SAMEORIGIN;`

## Actual behavior

Iframe in the UI was blank.

## Steps to reproduce

From configuration.yaml:
```
panel_iframe:
  terminal:
    title: Pi-hole
    icon: mdi:block-helper
    url: https://SERVER:PORT/admin/index.php
```

**Comment by frenck** [comment]
Fixed in version v0.2.1 which is now available in your Hass.io panel.
