### ISSUE TITLE
the 'total blocked today' goes down as well as up ?

### ISSUE THREAD

**Issue by magiva** [hassio-addons/addon-pi-hole#100]
# Problem/Motivation
I notice that the 'total blocked today' both in the web page and home assistant sensor, goes down as well as up, there doesnt seem to be an explanation for this.

> (Why the issue was filed)
i dont undestand why it goes down, the title suggests it increments

## Expected behavior
i expected it to increment in the day and then reset at midnight

## Actual behavior
it goes down as well as up

## Steps to reproduce
just watch it or look at the home assistant history for the sensor

> (How can someone else make/see it happen)
add 'Pi-Hole Ads Blocked Today' sensor to home assistant then look at its history

## Proposed changes
explain why it is a fluctuating figure, rename the title or fix it so it increments

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by magiva** [comment]
![image](https://user-images.githubusercontent.com/7522405/65337189-02e4c500-dbc8-11e9-8eee-e4c222a63b5f.png)

**Comment by frenck** [comment]
It shows the number of ads blocked the last 24 hours... (it shifts)
