### ISSUE TITLE
DNS Service not running, FTL Service offline

### ISSUE THREAD

**Issue by dwl99** [hassio-addons/addon-pi-hole#104]
I’m running pi-hole inside Hassio in a Docker container on my Synology NAS and changed the Primary DNS settings on my Amplifi HD router to the Synology’s IP address and left the Secondary DNS blank.

My setup is Internet <-> Virgin Superhub3 (modem mode) <-> Amplifi <-> Synology (all ethernet).

I installed pi-hole and can log into the web UI but it says that the DNS service is not running and the FTL service is offline.

The config file is:
```
{
  "update_lists_on_start": true,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "",
  "ipv6_address": "",
  "virtual_host": "pi-hole",
  "hosts": []
}
```
I’m a bit of a noob and would appreciate any pointers.

Thanks

**Comment by sinclairpaul** [comment]
Can you please post the addon startup log?

**Comment by dwl99** [comment]
startup log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Pi-hole
 Network-wide ad blocking using your Hass.io instance
-----------------------------------------------------------
 Add-on version: 4.0.0
 You are running the latest version of this add-on.
 System: null  (amd64 / qemux86-64)
 Home Assistant version: 0.100.1
 Supervisor version: 189
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] patches.sh: executing... 

[cont-init.d] patches.sh: exited 0.
[cont-init.d] pihole.sh: executing... 


  [✓] Password Removed

dnsmasq: cannot read /etc/dnsmasq.d//01-pihole.conf: Permission denied
  [i] Pi-hole blocking is enabled
  [i] Neutrino emissions detected...

  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [i] Status: Pending...

  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [i] Status: Pending...

  [✓] Status: No changes detected

  [i] Target: sysctl.org (hosts)
  [i] Status: Pending...
```

**Comment by sinclairpaul** [comment]
Not 100% sure but it may be an issue in detecting the interface.  Can you uninstall and reinstall and share the log with `"log_level": "info"` set?

What OS is this?, will also assume that the local server has static DNS entries assigned and any local DNS service is removed?

**Comment by dwl99** [comment]
It's Synology DSM 6.2.2 running in a Docker container. Will get onto removing & reinstalling it with logs later!

**Comment by sinclairpaul** [comment]
There is a typo in my comment sorry, I mean `"log_level": "debug"`

**Comment by dwl99** [comment]
I'm thinking it might be a permissions issue from re-reading the log:
`dnsmasq: cannot read /etc/dnsmasq.d//01-pihole.conf: Permission denied`
Unfortunately I do not have root access to try to fix this.

**Comment by dwl99** [comment]
I eventually abandoned trying to get this to run inside hassio & just did a regular Docker installation following these rather helpful instructions https://mariushosting.com/how-to-install-pi-hole-on-your-synology-nas/
I'm sure my problems were due to having no write permissions to the /etc folder.

**Comment by sinclairpaul** [comment]
Glad you managed to get what you needed.
