### ISSUE TITLE
Example Home Assistant configuration.yaml needs to be updated (breaking changes in Home Assistant 0.99)

### ISSUE THREAD

**Issue by jmpavlec** [hassio-addons/addon-pi-hole#109]
Example configuration is outdated and does not work after a refactor for pi_hole:
https://github.com/hassio-addons/addon-pi-hole/blob/v4.0.0/README.md#using-the-pi-hole-sensor-in-home-assistant

Refactored in: https://github.com/home-assistant/home-assistant/pull/25837

Update it or just link to: https://www.home-assistant.io/integrations/pi_hole/

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-pi-hole">hassio-addons/addon-pi-hole</a></strong></div><div>Pi-hole - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-pi-hole</div></blockquote>
<blockquote><img src="https://www.home-assistant.io/images/default-social.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/integrations/pi_hole/">Pi-hole</a></strong></div><div>Instructions on how to integrate Pi-hole with Home Assistant.</div></blockquote>

**Comment by sinclairpaul** [comment]
Thanks, there is a PR in flight to address this #102
