### ISSUE TITLE
Feature Request - Local DNS Entries

### ISSUE THREAD

**Issue by traslin** [hassio-addons/addon-pi-hole#11]
# Problem/Motivation

> Feature request for local DNS entries to resolve a local hostname within local network

## Proposed changes

> Add entries to the pi-hole configuration that allow the user to specify local DNS entries

**Comment by frenck** [comment]
Hi @traslin,

Thank you for your issue. Nevertheless, this feature was already requested in issue #9.
Therefore closing this issue.
