### ISSUE TITLE
Config setting for `hosts` don't work, because it uses /etc/hosts.list instead of /etc/hosts

### ISSUE THREAD

**Issue by andygrunwald** [hassio-addons/addon-pi-hole#115]
## System Information
* Pi-hole v4.0.0

## Problem/Motivation

I installed the piHole addon via the Hass.io Addon-Store and configured two custom domains:

```
{
  "update_lists_on_start": false,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "",
  "ipv6_address": "",
  "virtual_host": "",
  "hosts": [
    {
      "name": "hass.home",
      "ip": "192.168.178.61"
    },
    {
      "name": "mqtt.home",
      "ip": "192.168.178.61"
    }
  ]
}
````

## Expected behavior

I expect to happen that `mqtt.home` will resolve to `192.168.178.61`

## Actual behavior

```
$ ping mqtt.home
ping: cannot resolve mqtt.home: Unknown host
```

## Steps to reproduce

1. Install the Hass.io AddOn
2. Configure it like above and re-route your DNS to your piHole
3. Flush your DNS
4. Try to resolve `mqtt.home`

## Proposed changes

In https://github.com/hassio-addons/addon-pi-hole/blame/8e998e99f6ef20cd71b15c14e8989348315fe2e0/pi-hole/rootfs/etc/cont-init.d/pihole.sh#L199 the `hosts` configuration is written to `/etc/hosts.list`.

I can also confirm this, while login into the piHole docker container:
```
root@a0d7b954-pi-hole:/$ cat /etc/hosts.list
192.168.178.61 hass.home
192.168.178.61 mqtt.home
```

Based on my knowledge, the file `/etc/hosts.list` is not used or included in any of the applications _piHole_ or _dnsmasq_.
I guess the data should be written to `/etc/hosts`.
This is one possible solution. And from what I know, this would also work (not tested yet).
It is proposed in https://github.com/pi-hole/pi-hole/issues/975

A cleaner way would be using _dnsmasq_ and adding custom DNS records.
This is described by @Zixim in https://github.com/pi-hole/pi-hole/issues/975#issuecomment-548375915

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-pi-hole">hassio-addons/addon-pi-hole</a></strong></div><div>Pi-hole - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-pi-hole</div></blockquote>

**Comment by frenck** [comment]
This feature is likely to be removed from the add-on, since it was originally a workaround for something Pi-hole doesn't provide.

Since this is not a Pi-hole feature, it should be removed.

If you want a similar add-on that does provide these features, I would suggest on looking into AdGuard.

**Comment by andygrunwald** [comment]
I (partially) agree with you.
As described in https://github.com/pi-hole/pi-hole/issues/975#issuecomment-548375915, it is a _dnsmasq_ feature (that is used by piHole).

Digging a bit deeper, the `/etc/hosts.list` file is included. See

```
root@a0d7b954-pi-hole:/$ cat /etc/dnsmasq.d/99-addon.conf
user=pihole
group=pihole
no-hosts
addn-hosts=/etc/hosts.list
port=53
```

In theory, this change should be quite easy.

1. Replacing `echo "${ip} ${name}" >> /etc/hosts.list` in [/pi-hole/rootfs/etc/cont-init.d/pihole.sh](https://github.com/hassio-addons/addon-pi-hole/blob/8e998e99f6ef20cd71b15c14e8989348315fe2e0/pi-hole/rootfs/etc/cont-init.d/pihole.sh) with `echo "host-record=${name},${ip}" >> /etc/dnsmasq.d/99-addon.conf`
2. Removing line `addn-hosts=/etc/hosts.list` from [/pi-hole/rootfs/etc/dnsmasq.d/99-addon.conf](https://github.com/hassio-addons/addon-pi-hole/blob/8e998e99f6ef20cd71b15c14e8989348315fe2e0/pi-hole/rootfs/etc/dnsmasq.d/99-addon.conf)
3. Apply a `pihole restartdns` after the loop

This would not break with your rules, because this is supported by dnsmasq (which is the foundation of pihole). pihole just did not find time yet, to implement something like this in their webui. See https://github.com/pi-hole/pi-hole/issues/975

What do you think about this?
Would you accept such a feature?

**Comment by frenck** [comment]
Pi-hole does not use DNSMasq, they use FTL (which is a, IMHO worse, fork of DNSMasq).

Since this feature is not a Pi-hole feature, I will remove it.

**Comment by andygrunwald** [comment]
I see. Sad, because I believe this is a great feature.
And after digging a bit deeper, I did not find the root cause of why the host-config is not working.

According to http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html, the configuration makes sense and my bug report is not good enough.

Anyway, you took the decision. Thanks for your effort here!

**Comment by Pre10der** [comment]
This seems to be working fine for me (4.0.0). I have two host entries and both resolve perfectly fine. I use the nslookup command explicitly pointing to the pi-hole add-on to test. e.g. `nslookup hass.domain.com 192.168.0.2 `

My entries are as per the doco.

@frenck - please don't remove this feature. It's a necessary thing for split-brain DNS scenarios so that I can access HASS.IO locally on my LAN. Love your work @frenck!

**Comment by frenck** [comment]
Tested in the latest release, it works fine.

**Comment by andygrunwald** [comment]
Thank you. Confirmed
