### ISSUE TITLE
`%hassio_dns%` variable is not replaced in `/data/pihole/dns-servers.conf`

### ISSUE THREAD

**Issue by andygrunwald** [hassio-addons/addon-pi-hole#116]
## System Information

* Pi-hole v4.0.0

## Problem/Motivation

A variable is not replaced during installation properly

## Expected behavior

```
root@a0d7b954-pi-hole:/$ cat /data/pihole/dns-servers.conf
Hass.io DNS;%%hassio_dns%%;;
Google (ECS);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS);208.67.222.222;208.67.220.220;2620:0:ccc::2;2620:0:ccd::2
[...]
```

## Actual behavior

```
root@a0d7b954-pi-hole:/$ cat /data/pihole/dns-servers.conf
Hass.io DNS;%%hassio_dns%%;;
Google (ECS);8.8.8.8;8.8.4.4;2001:4860:4860:0:0:0:0:8888;2001:4860:4860:0:0:0:0:8844
OpenDNS (ECS);208.67.222.222;208.67.220.220;2620:0:ccc::2;2620:0:ccd::2
[...]
```

## Steps to reproduce

1. Install the Hass.io AddOn
2. Login into the docker container `docker exec -it <container name> /bin/bash`
3. Execute `cat /data/pihole/dns-servers.conf`

## Proposed changes

The variable is planned to replace here: https://github.com/hassio-addons/addon-pi-hole/blob/8e998e99f6ef20cd71b15c14e8989348315fe2e0/pi-hole/rootfs/etc/cont-init.d/pihole.sh#L35

## Open question

Any help/tips to debug this?
E.g. how do I check what `$(bashio::dns.host)` returns?

**Comment by sinclairpaul** [comment]
The addon makes a call to the supervisor to get the DNS servers configured.  As a hunch I am guessing firewalld or something similar may be involved here, which is possibly blocking traffic on the docker network.

**Comment by andygrunwald** [comment]
All docker containers run on the same machine:

```
root@home-automation:~# docker ps
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
3fc950916ace        hassioaddons/pi-hole-amd64:4.0.0                "/init"                  2 hours ago         Up 2 hours                                                                               addon_a0d7b954_pi-hole
e19dd7ef51da        homeassistant/intel-nuc-homeassistant:0.104.3   "/bin/entry.sh pytho…"   31 hours ago        Up 4 hours                                                                               homeassistant
c3eb414b4f55        homeassistant/amd64-addon-configurator:4.2      "/run.sh"                2 weeks ago         Up 2 weeks                                                                               addon_core_configurator
0893aa6ebb8a        homeassistant/amd64-addon-deconz:5.1            "/run.sh"                2 weeks ago         Up 2 weeks                                                                               addon_core_deconz
cd5e8610b942        homeassistant/amd64-addon-mosquitto:5.1         "/run.sh"                2 weeks ago         Up 2 weeks          0.0.0.0:1883-1884->1883-1884/tcp, 0.0.0.0:8883-8884->8883-8884/tcp   addon_core_mosquitto
a75b4ea84437        homeassistant/amd64-hassio-dns:1                "coredns -conf /conf…"   2 weeks ago         Up 2 minutes                                                                             hassio_dns
666fdf744cbb        homeassistant/amd64-hassio-supervisor           "/bin/entry.sh pytho…"   2 weeks ago         Up 2 minutes                                                                             hassio_supervisor
r
```

Any idea on how to debug this?
How do I know what is running behind the scenes of  `$(bashio::dns.host)` ?

**Comment by sinclairpaul** [comment]
Sure, the library is found at https://github.com/hassio-addons/bashio/blob/18827701868f28ffea50122c2b722947bae80e1f/lib/dns.sh#L97

What OS do you run?, I still believe you likely have something that is blocking connections on the docker network which will cause far more issues in the future.

**Comment by andygrunwald** [comment]
Thanks for the link. Not quite sure in which actual command `bashio::dns 'dns.info.host' '.host'` will translate.
Are there a few more docs about the `bashio` on the architecture or design of this "framework"?

For the OS question:
```
$ uname -a
Linux home-automation 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

I am thankful for any more debugging tips.

**Comment by sinclairpaul** [comment]
It is making a call to the Supervisor API the documentation of which can be found at:

https://github.com/home-assistant/hassio-supervisor/blob/dev/API.md#dns

You can see the structure of the call by looking at:

https://github.com/hassio-addons/bashio/blob/18827701868f28ffea50122c2b722947bae80e1f/lib/api.sh

I believe that Hass.io itself uses Networkmanager to get the local configured DNS servers, is that installed?  Also to check, the server itself has statically configured DNS?

**Comment by sinclairpaul** [comment]
Also to summarise, run this from your container and check the supervisor log:

`curl http://hassio/dns/info -H "X-HASSIO-KEY: ${HASSIO_TOKEN}"`

**Comment by andygrunwald** [comment]
@sinclairpaul network manager is not installed. According to the documentation (see https://www.home-assistant.io/hassio/installation/#debianubuntu), it is optional.

In the logs I see lines like
```
0-02-05 16:21:22 WARNING (MainThread) [hassio.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-02-05 16:21:22 WARNING (MainThread) [hassio.dbus.nmi_dns] No DnsManager support on the host. Local DNS functions have been disabled.
```

Based on this message, I found https://github.com/home-assistant/hassio-installer/issues/43, then a PR that it NetworkManager is not optional anymore (see https://github.com/home-assistant/hassio-installer/pull/36). To be honest, I don't really understand why NetworkManager is needed, what it is used for and if it is now required or optional.

The doc is saying (in a Warning field)
> Without the NetworkManager, you will be not able to control your host network setup over the UI.

The [README](https://github.com/home-assistant/hassio-installer) of the hassio-installer writes;
> Important: Don't only install NetworkManager, you need also use it on your system.

additionally marks the network-manager package as optional in the requirements.
Also from the _important_ note, it is not clear that I need to install it.

Sadly, the PR https://github.com/home-assistant/hassio-installer/pull/36 doesn't explain why this is needed.

Don't get me wrong, I am not complaining. I just try to understand the following questions:

- Why does hass.io need network-manager?
- Which explicit responsibility has this component towards hass.io? (or even more in detail: Which calls are executed from hass.io towards network manager)?
- Is it now optional or required? (different sources, say different things)
- Does the system work with (yes it does, but partially) or what implications does it have?

I am open to extending the documentation in several locations, but it is a bit hard for me to do this without the context.
Would be cool to provide the source code part which interacts with the network manager or issues that explain why this is needed, required or more context in this direction.

**Comment by sinclairpaul** [comment]
All great questions, but I think we have gone very far off-topic for the actual addon, as this appears to be an issue relating to the supervisor itself.

The repo is at https://github.com/home-assistant/supervisor I would suggest logging the questions there.

However one thing you didn't confirm is if installing NetworkManager actually fixes the issue or not?

**Comment by andygrunwald** [comment]
@sinclairpaul Thanks for your time. I opened an issue, see https://github.com/home-assistant/supervisor/issues/1488

> However one thing you didn't confirm is if installing NetworkManager actually fixes the issue or not?

I did not install the component NetworkManager, because I don't understand why this is needed at all or more, for what it is needed.
The docs say "don't just install it, use it". Ok, means, I need to configure it on the system. But what is the minimum configuration here? Or which parts do I need to use to get it working with Home Assistant (Core)? I assume network-manager has far more capabilities.

I doubt that just installing it, will solve this issue here. And it won't solve the issue for future users running in a similar issue. I am open to putting work into it, document it and solve it but it seems to be quite hard to understand the thought process + context of this in the project of Home Assistant.

**Comment by andygrunwald** [comment]
I dug a bit deeper:
I use the pi-Hole Add-on in v4.0.0 (`hassioaddons/pi-hole-amd64:4.0.0`) (latest version at the moment).
The container v4.0.0 of this addon is built upon `hassioaddons/base:4.1.1` (see https://github.com/hassio-addons/addon-pi-hole/blob/v4.0.0/pi-hole/Dockerfile#L1).
Or more in detail on `hassioaddons/base-amd64:4.1.1`, see https://github.com/hassio-addons/addon-pi-hole/blob/v4.0.0/pi-hole/build.json#L5.

The container `hassioaddons/base-amd64:4.1.1` is using bashio v0.4.1, see https://github.com/hassio-addons/addon-base/blob/v4.1.1/base/Dockerfile#L58

bashio v0.4.1 determines the Auth-Key to communicate with the supervisor here: https://github.com/hassio-addons/bashio/blob/4a37f124cd728368dec4c739d9a2938afdbfd2a4/lib/api.sh#L33-L35

If i login into my piHole container and check which env var is set:
```
$ echo ${HASSIO_TOKEN}
a07....
$ echo ${__BASHIO_HASSIO_TOKEN}

```

As a result: The used token (`__BASHIO_HASSIO_TOKEN`) is not set.
I also debugged the curl call that bashio is doing:

```
$ curl --silent --show-error  --write-out '\n%{http_code}' --request "GET" -H "X-HASSIO-KEY: " -H "Content-Type: application/json" -d "{}" http://hassio/dns/info
401: Unauthorized

$ curl --silent --show-error  --write-out '\n%{http_code}' --request "GET" -H "X-HASSIO-KEY: a07...." -H "Content-Type: application/json" -d "{}" http://hassio/dns/info
{"result": "ok", "data": {"version": "1", "latest_version": "1", "host": "172.30.32.3", "servers": [], "locals": []}}
```

Using the auth token that is stored in ${HASSIO_TOKEN} works.
I don't know why `${__BASHIO_HASSIO_TOKEN}` is not set. There is a test to set this, see https://github.com/hassio-addons/bashio/blob/v0.4.1/lib/bashio.sh#L29

A few questions:
- Where is `HASSIO_TOKEN` injected / created for pi hole?
- Can we upgrade to the latest base image? According to the `/etc/hosts` of the pihole container, hassio + supervisor entries are there. With the latest bashio version, this might work

**Comment by frenck** [comment]
@andygrunwald Not sure how you came to that conclusion, but it is way off and confusing. If the token wasn't working, the add-on would not even start.

**Comment by frenck** [comment]
The problem/root cause, it the missing NetworkManager here, which is a requirement nowadays. Please install it.

**Comment by andygrunwald** [comment]
> Not sure how you came to that conclusion, but it is way of, confusing, and above all, incorrect.

What conclusion you are referring to?
And would you mind to help me to say what is incorrect in particular and how it is correct?
Don't get me wrong, but I try to understand how it is built, and it is not as easy due to missing documentation/write ups.

> The problem/root cause, it the missing NetworkManager here, which is a requirement nowadays. Please install it.

Please have a look at https://github.com/home-assistant/supervisor/issues/1488
Network manager is marked as optional in nearly every documentation.
I don't understand why network manager is needed at all - because it is quite often use on desktop systems and not on server systems.

**Comment by frenck** [comment]
> And would you mind to help me to say what is incorrect in particular and how it is correct?

All of it.

> Network manager is marked as optional in nearly every documentation.

Sure, the documentation might be off, that is not an issue for this add-on though. Normally, I would recommend filing an issue upstream, but you have done that already.

> I don't understand why network manager is needed at all - because it is quite often use on desktop systems and not on server systems.

Ok. Not sure how that relates to the add-on, it uses a API provided by the Supervisor. This discussion you are trying to unchain does not belong here.

> and it is not as easy due to missing documentation/write ups.

I don't see where documentation is missing in this case, but feel free to open up PR's or issues where you think is needed. Also, not a concern for this add-on or issue.

**Comment by frenck** [comment]
The actual issue is that the add-on writes the DNS servers to an incorrect location.

This will be addressed in the next iteration. This can't be hot patched right now, because of tons of changes upstream.
