### ISSUE TITLE
Hosts within Network list doesn't link correctly to query page

### ISSUE THREAD

**Issue by guice** [hassio-addons/addon-pi-hole#117]
# Problem/Motivation

Using pi-hole addon through HA: the links on the "Networks" tab are pointing to host/admin/queries, not hassio_ingress, and failing.

<img width="1542" alt="Screen Shot 2020-02-07 at 2 08 42 PM" src="https://user-images.githubusercontent.com/205378/74066112-b4d43080-49b3-11ea-9a3d-37dec8f769d4.png">

## Expected behavior

It needs to route through the HA Ingress route, e.g. 

* https://myhostname.com:8123/api/hassio_ingress/bYKAB0kcZqZsPk0pEAGPi4U9uvcZaqEAVrQU5Me_6h8/queries.php?client=192.168.0.1

## Actual behavior

Goes to the host directly:

* https://myhostname.com:8123/admin/queries.php?client=192.168.0.1

## Steps to reproduce

?? Click on Network, click an IP. 

May be related to defining a `virtual_host` within the config.

**Comment by sinclairpaul** [comment]
#97 #98 Would resolve.

Needs a new release for the changes.

Duplicate of #92

**Comment by guice** [comment]
Ah, I see. Thanks, I guess I'll close this out then. I looked at open issues, didn't search for closed issues. This is a fresh Pi-hole install.
