### ISSUE TITLE
Local host names not showing (only IP showing)

### ISSUE THREAD

**Issue by HunterDG** [hassio-addons/addon-pi-hole#119]
# Problem/Motivation

> https://github.com/hassio-addons/addon-pi-hole/issues/78 was closed

## Expected behavior

> pi.hole add-on resolves local hostnames

## Actual behavior

> seems like the add-on initially resolved some hostnames, but no longer does.  I cannot reproduce the initial successful behavior even with add-on uninstall/reinstall/fresh config

## Steps to reproduce

> enable conditional forwarding to upstream router
> disable "never forward" options
> expect local hostnames to resolve

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by RyanMorash** [comment]
I am also running into the same issue
HassOS 3.12
Supervisor 209
Pi-hole Addon 4.1.1

**Comment by t0bse** [comment]
same here - could be since fritz OS 7... ?

**Comment by frenck** [comment]
This add-on is now deprecated and will no longer receive updates or fixes.
