### ISSUE TITLE
Pi-hole blocking FTP

### ISSUE THREAD

**Issue by johnnysmithy852456** [hassio-addons/addon-pi-hole#120]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Would need a few more details on the issue as per the template, not much we can do with this.
