### ISSUE TITLE
Adding DoH Support

### ISSUE THREAD

**Issue by FrancYescO** [hassio-addons/addon-pi-hole#121]
# Problem/Motivation

> I want to enable DoH on my Pi-Hole instance, but actually the only way is to manually enter in the container to install cloudflared and etc.

## Actual behavior

> No cloudflared installed in the image

## Proposed changes

> add an option to the hassio configuration that will take care of installing cloudflared and setup the local DoH dns resolution (127.0.0.1#5053) basically, automatically reproduce the steps of the docs: https://docs.pi-hole.net/guides/dns-over-https/

<blockquote><img src="../../images/favicon.ico" width="48" align="right"><div><strong><a href="https://docs.pi-hole.net/guides/dns-over-https/">Configuring DNS-Over-HTTPS on Pi-hole - Pi-hole documentation</a></strong></div></blockquote>

**Comment by frenck** [comment]
Pi-hole does not support DoH.

Your suggestion is to install CloudFlared (not Pi-hole). This does not belong in this add-on, but in a separate add-on.

**Comment by FrancYescO** [comment]
Simple instructions for who is interested and running hassio in docker:
Start cloudflared container in your host:
`docker run -d --restart=always --name cloudflared -p 5053:5053/udp crazymax/cloudflared:latest`
than in set `127.0.0.1#5053` as upstream dns in Pi-Hole:
<img width="990" alt="immagine" src="https://user-images.githubusercontent.com/4574593/74587410-5b42b600-4ff2-11ea-95df-149a30376358.png">

Check https://1.1.1.1/help to know all is working as expected, enabling DNSSEC on Pi-Hole will break DoH detection.
