### ISSUE TITLE
addon won't start using ssl true 

### ISSUE THREAD

**Issue by keiser1080** [hassio-addons/addon-pi-hole#125]
# Problem/Motivation

> the addon don't start  when ssl is set to true
## Expected behavior

> start pihole using ssl

## Actual behavior

> the log show
[17:24:09] FATAL: Unfortunately, the file specified in the
[17:24:09] FATAL: 'certfile' option does not exists.
even if the file exist and the write are correct:
chown root:root fullchain.pem privkey.pem
chmod 600 fullchain.pem privkey.pem

root@orangepipc:/usr/share/hassio/homeassistant/ssl# ls -al
total 16
drwxr-xr-x  2 root root 4096 févr. 16 22:09 .
drwxr-xr-x 12 root root 4096 mars   1 17:16 ..
-rw-------  1 root root 3558 févr. 16 22:09 fullchain.pem
-rw-------  1 root root 1708 févr. 16 22:09 privkey.pem
## Steps to reproduce

> set the ssl to true

**Comment by frenck** [comment]
I'm unable to reproduce this on my end. Tested on 3 different setup's, all were able to enable SSL.

**Comment by keiser1080** [comment]
> I'm unable to reproduce this on my end. Tested on 3 different setup's, all were able to enable SSL.

is there any log i can share ?
Could you point me the file ?

**Comment by keiser1080** [comment]
it's working now
i found something very strange.
home assistant use the path /usr/share/hassio/homeassistant/ssl/ for the certificate
pihole use the path /usr/share/hassio/ssl/ for the certificate.
I will check with other addons wich path is used.

i temporaly copi the certificate in both path.
I will do later a symplink.

`cp /usr/share/hassio/homeassistant/ssl/* /usr/share/hassio/ssl/`

Wich path should be used for the certificat?

**Comment by frenck** [comment]
`/ssl` is not strange, that is where it should be and is documented as such as well. You should not store your SSL certificates in your Home Assistant configuration folder.

Glad it is resolved.

**Comment by keiser1080** [comment]
thanks !
