### ISSUE TITLE
Is there any way to use Unbound dns resolver?

### ISSUE THREAD

**Issue by Razer0123** [hassio-addons/addon-pi-hole#128]
# Problem/Motivation

I would like to use Unbound to resolv my own DNS queries with HASS

## Expected behavior

Be able to use it

## Actual behavior

Not currently available as far as i know

## Proposed changes

Add the possibility to use unbound

**Comment by sinclairpaul** [comment]
No you cannot, if the concern is DNS over TLS/HTTPS you may wish to look at Adguard which natively supports it.
