### ISSUE TITLE
Unable to upload debug logs to Pi-Hole team

### ISSUE THREAD

**Issue by svh1985** [hassio-addons/addon-pi-hole#129]
# Problem/Motivation
I want to get support on the Pi-Hole community which requires me to upload the debug log.
This can be done by the webinterface (Tools->Generate debug log) or command line running: pihole -d

## Expected behavior
Succesfull upload and retrieval of token that can be shared to the Pi-Hole team.

## Actual behavior
Got this error:
```
[✗]  There was an error uploading your debug log.
   * Please try again or contact the Pi-hole team for assistance.
   * A local copy of the debug log can be found at: /var/log/pihole_debug.log
```

## Steps to reproduce
See steps above
> (How can someone else make/see it happen)

**Comment by frenck** [comment]
This is correct. They do not support the add-on either.
