### ISSUE TITLE
v3.2 Updates for core, adminLTE and FTL

### ISSUE THREAD

**Issue by ggamel** [hassio-addons/addon-pi-hole#13]
# Problem/Motivation
> Both Pi-hole core and Admin page were updated to v3.2, respectively.

## Expected behavior

> The Pi-hole add-on for hassio provides access to these major updates

## Actual behavior

> The v3.2 updates are unavailable as of yet

## Steps to reproduce

> The updates are not available via the addon-pi-hole

## Proposed changes

> See https://github.com/pi-hole/pi-hole/releases/tag/v3.2
> &
> https://github.com/pi-hole/AdminLTE/releases/tag/v3.2
>
> These are major updates.

**Comment by frenck** [comment]
Finally! 🕺 
I think this might take some effort and time since the change is pretty big!

So please bear with me.

**Comment by ggamel** [comment]
@frenck I'm totally new to Pi-hole, but this seems like a huge update. Thanks for the work you do, though, with your add-ons. Much appreciated! 👍 👏 🎉

**Comment by frenck** [comment]
Well ok... that was not that hard.
Needs some more testing, but I think I've got it done.

**Comment by diginc** [comment]
Since you're also using alpine we may have some some similar issues: https://github.com/diginc/docker-pi-hole/pull/192

**Comment by frenck** [comment]
@diginc We probably do, I'll push out the changes this weekend. I'm actually done and have everything in a working state (still running a lot of tests at this moment).

**Comment by frenck** [comment]
Just released v0.4.0 of the add-on!
