### ISSUE TITLE
Pi Hole + Portainer + Home Assistant (Hassio) on Ubuntu 

### ISSUE THREAD

**Issue by SHHA24** [hassio-addons/addon-pi-hole#130]
Anyone able to help? 
followed the install instruction and the setup, but PiHole will not run the DNS.
i think this is to do with the Portainer, so tried adding in some ports from container to host...

does anyone have instruction on how best to setup Pi Hole running on Portainer? 

thanks

**Comment by frenck** [comment]
Don't manage the Home Assistant ecosystem with Portainer, it will cause your problems since Home Assistant manages Docker for you.

If you interfere with that, you will end up having problems, which are yours to solve.
