### ISSUE TITLE
Invalid addon appearing in sidebar

### ISSUE THREAD

**Issue by kaizersoje** [hassio-addons/addon-pi-hole#132]
Hi,
I am getting this Pi-hole addon appearing in my sidebar. 
![hassio sidebar](https://user-images.githubusercontent.com/54566217/77970194-4ff3e180-7337-11ea-847a-3b780b3472d6.png)

However, this addon is not installed. 
![hassio addons](https://user-images.githubusercontent.com/54566217/77970261-774aae80-7337-11ea-87f9-fc19f9b80173.png)

When I click on the sidebar addon, I get the following screen.
![addon screen](https://user-images.githubusercontent.com/54566217/77970410-ddcfcc80-7337-11ea-9e3e-8250e0968a40.png)

Please help.

**Comment by frenck** [comment]
That is not an add-on issue, as the add-on itself doesn't manage that.
Furthermore, by the looks of the IP address in that error message, I look like a panel_iframe to me (which is a Home Assistant manual configuration in the YAML).

If the issue persists, please raise an issue with Home Assistant.
