### ISSUE TITLE
Pi-Hole not accessible on external network

### ISSUE THREAD

**Issue by mpgoebel** [hassio-addons/addon-pi-hole#14]
# Problem/Motivation

Not able to access Pi-Hole from outside of local network

## Expected behavior

Access with xxxx.Duckdns.org:80 since forwarding is setup.

## Actual behavior

Only opens when connect to local network

I have looked on the forums and asked the question in the Discord chat with no help, I have double and triple checked my network settings and everything appears to work, I have many ports forwarded with no problems. 

This is the settings I am using
```
{
  "log_level": "trace",
  "password": "",
  "update_lists_on_start": true,
  "web_port": 80,
  "dns_port": 53,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "",
  "ipv6_address": "",
  "virtual_host": "myipaddress.duckdns.org",
  "hosts": []
}
```
Here is a snippet of my Log file, nothing seems to be recorded when I attempt to open the web ui from work,  I have also not been able to see anything from the Pi-hole sensor in Hass.io.

```
dnsmasq: query[A] api-global.netflix.com from 10.0.0.20
dnsmasq: cached api-global.netflix.com is <CNAME>
dnsmasq: cached api-global.geo.netflix.com is <CNAME>
dnsmasq: forwarded api-global.netflix.com to 8.8.4.4
dnsmasq: forwarded api-global.netflix.com to 8.8.8.8
dnsmasq: reply api-global.netflix.com is <CNAME>
dnsmasq: reply api-global.geo.netflix.com is <CNAME>
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.10.59.119
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.26.90.140
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.33.161.173
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.10.85.197
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.25.230.252
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.27.139.245
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.10.200.73
dnsmasq: reply api-global.us-west-2.prodaa.netflix.com is 52.25.167.230
dnsmasq: query[A] spectrum.s3.amazonaws.com from 10.0.0.13
dnsmasq: cached spectrum.s3.amazonaws.com is <CNAME>
dnsmasq: cached s3-directional-w.amazonaws.com is <CNAME>
dnsmasq: forwarded spectrum.s3.amazonaws.com to 8.8.4.4
dnsmasq: reply spectrum.s3.amazonaws.com is <CNAME>
dnsmasq: reply s3-directional-w.amazonaws.com is <CNAME>
dnsmasq: reply s3-1-w.amazonaws.com is 52.216.84.131
dnsmasq: query[A] spectrum.s3.amazonaws.com from 10.0.0.12
dnsmasq: cached spectrum.s3.amazonaws.com is <CNAME>
dnsmasq: cached s3-directional-w.amazonaws.com is <CNAME>
dnsmasq: forwarded spectrum.s3.amazonaws.com to 8.8.4.4
dnsmasq: reply spectrum.s3.amazonaws.com is <CNAME>
dnsmasq: reply s3-directional-w.amazonaws.com is <CNAME>
dnsmasq: reply s3-1-w.amazonaws.com is 52.216.226.56
```

Sorry for the incomplete information!

**Comment by frenck** [comment]
Please provide some more information, like settings, startup logs, describe the type of setup you are using, ...

**Comment by mpgoebel** [comment]
I have update the OP

**Comment by frenck** [comment]
Are you using http**s**://xxxx.Duckdns.org:80? Since you have enabled SSL in the configuration?

Secondly, be sure this is not a limitation in your router (try another port including forwarding to be sure).

**Comment by mpgoebel** [comment]
https://xxxx.duckdns.org:80/admin/index.php is what opens with the webui button.

Well I did get it working by changing to port 82, not sure why it doesn't like port 80.  Only downside to that is the open web ui button only opens on port 80, is there any other downside?

**Comment by frenck** [comment]
Yes, there are multiple downsides, as stated in the documentation.

In the ideal situation, Pi-hole is accessible on non-ssl and running on port 80, since it will handle the replacement of the blocked ads better. At the moment I'm looking for a method for allowing people to run the admin separate from the block page.

Other than that, you'll be fine! (I'm actually running my "production" installation in the same way).

The "Open Web UI" button has limitation for add-on developers. There is currently no way for me to inform Hass.io about the port change. So that is a Hass.io limitation, not something I can work around.

**Comment by mpgoebel** [comment]
I will keep it set with port 82 and keep a look out for any changes! I don't use the open UI button to access it anyway and now that the iframe works, I won't ever need to.  Thanks for you help and great work!

**Comment by frenck** [comment]
@mpgoebel You are welcome sir! 👍
