### ISSUE TITLE
Visiting blocked page with port number does not redirect to admin

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-pi-hole#2]
# Problem/Motivation

When visiting the block page using a port number, it does not redirect to the admin properly.

e.g.
`http://xxx.xxx.xxx.xxx:80/`

## Expected behavior

I expected to be redirected to the admin since I'm visiting the configured IP of Pi-hole

## Actual behavior

The block page is served.

## Steps to reproduce

Install and start the addon and visit the block page with the port number in the URL.

## Proposed changes

Patch the Pi-hole blocked page to handle port numbers correctly.

## Ref

https://community.home-assistant.io/t/repository-community-hass-io-add-ons/24705/166?u=frenck

**Comment by sml156** [comment]
That's not a bug it's expected behaviour, The way to view the admin page is

http://xxx.xxx.xxx.xxx/admin
or
http://pihole/admin

**Comment by frenck** [comment]
@sml156 Thank you for your addition, nevertheless, you are not completely right on this.

Pi-hole was not designed to run on different port numbers. The `Blocked Page` redirects the user when he visits one of the direct IP's or configured domains (e.g., `pi.hole`). This redirect function is broken now, since Hass.io will always add a port to the internal links. 

While this can be worked around, the main issue is that the blocked page does not take possible port numbers in URL's in account (it just simply fails at this). Using port 80 in your URL is perfectly valid and Pi-hole should not behave differently in that case.

**Comment by frenck** [comment]
Fixed on `master` branch. Will be included in the next release.
