### ISSUE TITLE
Logging functions (enable/disable/clear) don't seem to work

### ISSUE THREAD

**Issue by kevingrubbs** [hassio-addons/addon-pi-hole#20]
# Problem/Motivation
The buttons in the UI to enable/disable/clear the query log seem to make no difference.

## Expected behavior
1. Disabling the log would stop recording the traffic. 
2. Enabling would record traffic
3. Clear would erase the historic graph and "top blocked/requested domains"

## Actual behavior
All three of these functions seem to have no impact. Query logging seems to be on all the time, and there seems to be no way to clear the data.

**Comment by frenck** [comment]
@kevingrubbs Thank you for reporting this one. I will look into it as soon as possible.

**Comment by frenck** [comment]
Fix is implemented and merged into the master branch, will be released in v0.5.0
