### ISSUE TITLE
Cannot meaningfully define persistent custom upstream DNS servers

### ISSUE THREAD

**Issue by dfinlay** [hassio-addons/addon-pi-hole#23]
(Apologies upfront for the rambling stream of consciousness report.  I was investigating while writing it and ran out of time to make it more cohesive.)

# Problem/Motivation

> I installed this on my Hassio instance, and ran into some issues with local hostname resolution. My home network has dynamic FQDN assignment w/ PTR support, which I irrationally love.  DHCP and DNS are handled from a pfSense box, and I set pi-hole's upstream DNS servers to the pfSense box's IPs (v4&v6) and restarted the add-on. However, when I tried to resolve hosts I knew were resolvable via the pfSense the pi-hole failed to resolve properly.  I went through the logs and discovered that pi-hole was using Google's DNS servers (`8.8.8.8`, `8.8.4.4`) for resolution.  Even though I disabled them in the UI, the setting did not stick. To correct the behavior I had to select the empty radio boxes for Google DNS in Settings=>DNS and save, then unselect and save again.
>
> The cause of  appears to be the `PIHOLE_DNS*` options in [setupVars.conf|https://github.com/hassio-addons/addon-pi-hole/blob/master/pi-hole/rootfs/etc/pihole/setupVars.conf].  These are use on installation to populate initial settings in `/etc/dnsmasq.d/01-pihole.conf`. It appears either every time the add-on/service restarts it is regenerated from the `setupVars.conf` instead of using a persisted configuration. 
>
>So the core issue appears to be upstream (heh) with pi-hole proper and how it handles setup parameters and maintaining configuration state. It is in no way good practice to silently and invisibly overwrite user settings on service restart.

## Expected behavior

> Can configure custom upstream DNS servers.

## Actual behavior

> The default DNS Servers in `setupVars.conf` invisibly override custom upstream DNS servers on service start.

## Steps to reproduce

1. Navigate to the pi-hole DNS settings view (Settings => DNS).
2. Add a custom upstream DNS server, set the IP to OpenDNS (208.67.222.222) for consistency.
3. Disable the Google DNS entries.
4. Save the configuration.
5. While tailing the pi-hole logs^1, issue DNS queries and observe in the logs which upstream server they are being sent to. The upstream should be OpenDNS (208.67.222.222).
6. From Settings => System, select "restart Add-on"
7. After the service is available again, repeat step 5, but observe the upstream servers being used will be 8.8.4.4.
8. Navigate to the pi-hole DNS settings view (Settings => DNS).
9. Select all 4 radio boxes for Google DNS Servers and Save.
10. Deselect all 4 radio boxes for Google DNS Servers and Save.
11. Repeat Step 5 and observer the OpenDNS service is being used as the upstream again.

## Proposed changes

> To work around this issue, and provide a easy initial setup, it would be nice if the `config` data could include an `upstream` property.  It's typing would be `[str]` and the default value would be `["8.8.8.8", "8.8.4.4"]`. That would be used to append the `setupVars.conf` with `PIHOLE_DNS_{n}=upstream[n]` key/value pairs.

*Example Configuration*

```
{
  "log_level": "info",
  "password": "",
  "update_lists_on_start": true,
  "http_port": 80,
  "https_port": 443,
  "dns_port": 53,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "",
  "ipv6_address": "",
  "virtual_host": "",
  "hosts": [],
  "upstream": [
    "8.8.8.8",
    "8.8.4.4"
  ]
}
```

^1 Simple test queries:

```
#!/usr/bin/env bash
PIHOLE_IP='172.16.0.1'
TARGETS=('google.com', 'github.com', 'dropbox.com', 'xkcd.com', 'apple.com')

for TARGET in ${TARGETS[@]}; do
    dig "${TARGET}" A "@${PIHOLE_IP}" +nocmd +nocomments
done
```

**Comment by ax42** [comment]
+1 for this issue.

**Comment by frenck** [comment]
Thanks for your report, I will look into this.

> The default DNS Servers in `setupVars.conf` invisibly override custom upstream DNS servers on service start.

Setting custom DNS servers should be saved into `setupVars.conf` by Pi-Hole, so that should not be a problem. Secondly, `setupVars.conf` is persistent in this add-on.

So there must be something else wrong.

**Comment by dfinlay** [comment]
My proposed changed is probably not the correct one, I'll readily concede that.

I'm fairly sure the issue is in setupVars.conf, as that gets written in the container's entry point. Pi-hole may indeed write to them after a configuration change, but that gets overwritten if you restart the container.

**Comment by ax42** [comment]
I've had the explicit conversation with the docker-pi-hole devs that this is an issue and their response was that you should not be using setupVars (as it gets overwritten) but rather `-e` environment variables in the startup.

**Comment by dfinlay** [comment]
Thank you for looking in to it so diligently. 

I was half right, it was getting overwritten. I just had the wrong source. My proposed solution not so great.

**Comment by ax42** [comment]
@frenck it may be handled in the admin interface, but I don't think the change will persist.

**Comment by frenck** [comment]
I'll will look into this asap. Nevertheless, I've moved houses this weekend, so my life is in boxes right now. Please give me a little more time.

**Comment by frenck** [comment]
Debugged the issue. It is not an issue with the setupVars, it is in the dnsmasq part.

Will deploy a fix for this in de upcoming release.

**Comment by frenck** [comment]
Fixed in the `master` branch.
