### ISSUE TITLE
Teleporter error 500

### ISSUE THREAD

**Issue by NaffanDroo** [hassio-addons/addon-pi-hole#26]
# Problem/Motivation

> I normally run two pi-hole instances for failover, since switching to hass.io and using this add on, I have found that trying to run the teleporter to upload a backup from the other instance fails to load the page with error 500

## Expected behavior

> Running the telerporter import on my other instance results in the following:

```
Processing blacklist.txt
Processing whitelist.txt
Processing wildcardblocking.txt
OK
```

## Actual behavior
> HTTP Error 500

## Steps to reproduce

> Using version 1.0.1, Export config, import it - this fails even from the same instance

## Proposed changes

> N/A

**Comment by frenck** [comment]
I've been able to reproduce it.

Actual error in the error logs:
```
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type() in /var/www/html/admin/scripts/pi-hole/php/teleporter.php:96
```

Seems like the PHP `fileinfo` extension is required, which is indeed not installed in this add-on.

Awaiting implementation.

**Comment by frenck** [comment]
The missing PHP extension has been added and is currently fixed in the edge channel.
Will be part of the next release.
