### ISSUE TITLE
Allow "forwards" configuration option

### ISSUE THREAD

**Issue by cdrfun** [hassio-addons/addon-pi-hole#27]
# Problem/Motivation

To be a feature enriched alternative to the Dnsmasq addon, the PiHole addon should support the forwards configuration option

## Expected behavior

Apply the configuration option as described here https://www.home-assistant.io/addons/dnsmasq/

`  "forwards": [
    {"domain": "mystuff.local", "server": "192.168.1.40"}
  ],`

**Comment by frenck** [comment]
I agree with this, pretty good idea.
Nevertheless, this is currently not that high on my list of priorities.

**Comment by frenck** [comment]
I'm going to put this request on hold.
Pi-hole is planning to move away from dnsmasq and replacing it with their own fork for Pi-hole 4.0.

It is likely this still will work, is possible. Nevertheless, I want to make sure I'm not introducing new feature now, that require dnsmasq.

**Comment by frenck** [comment]
@cdrfun Pi-hole v4 now support a forwarding feature for the lookup of local stuff.

![image](https://user-images.githubusercontent.com/195327/44484739-dff78280-a64e-11e8-80e4-0ac70ff61301.png)

Would that satisfy your needs?

**Comment by cdrfun** [comment]
I'm not quite sure, and can't test it right now (It's not available for hass.io and I don't have the time to set it up separately). So I have some questions:

1) Is this only for internal resolution of client names displayed in the web ui? If that's the case querying PI Hole DNS would not forward the request, no?
2) Shouldn't it be a DNS server IP for the according local domain you have to provide?
3) To be able to resolve different local domains you would have to make multiple entries. In the Screenshot it looks as if only one DNS server/local domain can be supplied.

**Comment by frenck** [comment]
1. Unsure.
2. Unless you choose to use a public service like Cloudflare for all other requests...
3. Correct, only 1 entry possible.

I'm going to look into this after the v4.0 release. Reasoning:

- I don't want to postpone the release any longer
- I'm limited available in the upcoming weeks because of personal reasons.
- Give the add-on stability time on the (pretty major) upgrade it has already.

I will move this into the 2.1.x release of the add-on.

**Comment by cdrfun** [comment]
Ah, it sounds as it's not the wanted feature then. 
Here's a PI Hole forum entry from somebody who has done what I want. It would be great If that would be possible with hass.io, too.

https://discourse.pi-hole.net/t/how-to-forward-specific-domain-to-specific-upstream-server/4051

Maybe it's a good opportunity for me to have a closer look at addons - we'll see.

**Comment by frenck** [comment]
That is easily added, but I've just moved it outside of the "big" upgrade scope.

**Comment by frenck** [comment]
not stale... thanks bot 👍
