### ISSUE TITLE
Tip: Using PiHole as DNS server for Home Assistant and other addons

### ISSUE THREAD

**Issue by TechAsh** [hassio-addons/addon-pi-hole#30]
# Problem/Motivation

It is useful to be able to have other addons use the PiHole addon for DNS requests, but this won't work with the default config. The fix for this is easy, but not obvious.

## Expected behavior

Home Assistant and addons can use the PiHole addon for DNS requests.

## Actual behavior

DNS requests timeout.

## Proposed changes

Two simple config changes allow for this to work.
1. Set HassIO's static IP as a dns server in the ResinOS network config (Do not use 127.0.0.1 as Docker will ignore that). eg:

```
[ipv4]
address1=192.168.1.111/24,192.168.1.1
dns=192.168.1.111;8.8.8.8;8.8.4.4;
dns-search=lan.example.net
method=manual
```

2. In the PiHole Settings -> DNS tab, select "Listen on all interfaces, permit all origins".

I recommend including this information in the documentation.

**Comment by frenck** [comment]
I like this idea @TechAsh!

Since it is a nice-to-have, I've given this a low priority.
Feel free to open a PR if you'd like to add it yourself 😉

**Comment by wesmininger** [comment]
Hi - I am using HassOS vs resinOS what are the changes?

**Comment by frenck** [comment]
Second thought, while this works (and is pretty awesome).
I'm not going to recommend "Listen on all interfaces, permit all origins".

Therefore I'm closing this issue/suggestion for now.
