### ISSUE TITLE
hosts config directive seems to not work

### ISSUE THREAD

**Issue by Kedryn** [hassio-addons/addon-pi-hole#32]
# Problem/Motivation

I've run PiHole in Hassio with this parameter:

  "hosts": [
    {
      "name": "xxxxxx.duckdns.org",
      "ip": "192.168.0.48"
    }
  ]

## Expected behavior

With my router as the lan DNS, and the pihole as the router DNS, i expect to be able to resolve  xxxxxx.duckdns.org locally, not via google dns (that gives the public ip, not the lan one)

## Actual behavior

The PiHole does not resolve the host at all. It works for all other hosts, but does not resolve this one.

## Steps to reproduce

You can try same thing.

## Proposed changes

nope

**Comment by frenck** [comment]
I rely on the on my personal network, so I'm pretty sure it works...

**Comment by Kedryn** [comment]
For me it doesnt. I does not resolve the host, nor within the interal dns server, nor forwarding to esternal. Everything else works.

**Comment by frenck** [comment]
Could you please try this and provide me the output:

- Use your normal computer (so not from the SSH prompt of Hass.io)
- At a command prompt, type `nslookup`, and then press ENTER.
- Type `server <IP address>`, where IP address is the IP address of Hass.io system.
- Type `<domain name>`, where the domain name is the name of an external domain, and then press ENTER.

**Comment by Kedryn** [comment]
I did it this morning. When using my router as server (default) that forwards to pi-hole, i get timeout. If i use the pi-hole as the server, i get

> xxxxxx.duckdns.org
Server:  hassio.fritz.box
Address:  192.168.0.48

*** hassio.fritz.box non è in grado di xxxxxx.kedryn.duckdns.org: No response from server

I tried few minutes ago to stop pi-hole in my hassio, then i installed the dnsmasq addon, configured the same way, and i get different result. The Fritz timeouts, the hassio resolves.>

obviously i replaced true hostname by xxxxxx

**Comment by Kedryn** [comment]
nevermind, i've found the problem. It's the damn "DNS Rebind Potection" that is automatically enabled, and is on the LAN config page, not in the DNS one, of the FritzBox
I've put my host in the exception list, and now it works.
I'm closing this one
