### ISSUE TITLE
Pi-Hole Whitelisting of DNS Address not working through gui

### ISSUE THREAD

**Issue by MwC-Trexx** [hassio-addons/addon-pi-hole#33]
# Problem/Motivation

>When trying to whitelist a previously blocked domain, it appears to work in gui, but doesn't.

This was a bug in the pi-hole build used for the add-on and fixed in a subsequent release.

See: https://discourse.pi-hole.net/t/psa-having-whitelisting-issues-with-3-3-read-here/7393

## Proposed changes
Update to newer release of Pi-Hole.  

<blockquote><img src="https://discourse.pi-hole.net/uploads/default/original/1X/e8e33beef1d35f87a69e874f9e2a7b1a5800b93b.png" width="48" align="right"><div><img src="https://discourse.pi-hole.net/uploads/default/original/1X/e8e33beef1d35f87a69e874f9e2a7b1a5800b93b.png" height="14"> Pi-hole Userspace</div><div><strong><a href="https://discourse.pi-hole.net/t/psa-having-whitelisting-issues-with-3-3-read-here/7393">[PSA] Having Whitelisting issues with 3.3? Read here</a></strong></div><div>Hi All,  After a few days of pulling out our hair and troubleshooting this whitelisting issue that some of you have reported, we’re finally getting to the bottom of it.  The good news is, whitelisting is not completely broken. You can still whitelist domains from the cli with no issues by calling pihole -w [domain-to-whitelist]. The issue only affects whitelisting from the admin page (whitelist page, query log, and block page)  Take a look over this pull request where I’ve attempted to explain w...</div></blockquote>

**Comment by frenck** [comment]
The add-on will be moving to 4.0 soon.

**Comment by MwC-Trexx** [comment]
Is there a method for HASSOS to get “into” the docker container to be able
to leverage the CLI work arounds in the interim?


-- 
Paul Tisl
Sent with Airmail

On August 6, 2018 at 12:10:20 PM, Franck Nijhof (notifications@github.com)
wrote:

The add-on will be moving to 4.0 soon.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hassio-addons/addon-pi-hole/issues/33#issuecomment-410780494>,
or mute the thread

**Comment by frenck** [comment]
I've reproduced this issue on Pi-hole v4.0 as well.
I've found a possible solution, which I will be implementing as part of the v4 update
