### ISSUE TITLE
container won't start if a logfile exists

### ISSUE THREAD

**Issue by hobbypunk90** [hassio-addons/addon-pi-hole#36]
# Problem/Motivation

sometimes the container can't start because of an existing log file.

```
ln: failed to create symbolic link '/var/log/pihole.log': File exists,
[cont-init.d] 35-logfiles.sh: exited 1.,
[cont-finish.d] 99-message.sh: exited 0.,
[cont-finish.d] executing container finish scripts...,
-----------------------------------------------------------,
[cont-finish.d] 99-message.sh: executing... ,
                Oops! Something went wrong.,
 ,
 We are so sorry, but something went terribly wrong when,
 starting or running this add-on.,
 Be sure to check the log above, line by line, for hints.
```

## Expected behavior

the logs are deleted.

## Actual behavior

container shuts down

## Proposed changes

the script `35-logfiles.sh` have to delete the log file if it exists before creating the link.

**Comment by frenck** [comment]
You are on a roll! Sorry about this.
![bitmoji](https://render.bitstrips.com/v2/cpanel/d69b3df3-dae2-463d-8fa7-6070eafd7110-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)

**Comment by hobbypunk90** [comment]
😂 no problem, we are all human, we all do misstakes 😁

**Comment by frenck** [comment]
Well, this upgrade is pretty painful/large. I did a large number of tests, but that seems to be not sufficient.

**Comment by hobbypunk90** [comment]
i guessed 😁
i was little shocked this morning, waking up and can't stream music 😁

**Comment by OmgImAlexis** [comment]
Just happened to myself, updated all my containers and then did a reboot of the host machine; Now pi-hole won't start at all.

**Comment by frenck** [comment]
@OmgImAlexis 
Could you provide add-on logs? 👍

**Comment by OmgImAlexis** [comment]
Seems I couldn't update the container as my docker DNS was set to use my pi-hole thanks to my router(unifi usg). I can see others having this same issue.

**Comment by frenck** [comment]
@OmgImAlexis It is really recommended to NOT include your server to use the same DNS.
