### ISSUE TITLE
container shuts instantly down - don't set admin_port in nginx.conf

### ISSUE THREAD

**Issue by hobbypunk90** [hassio-addons/addon-pi-hole#37]
# Problem/Motivation

i'm not sure why, perhaps this problem interacts with the 2 other issues i created.
the admin_port from config isn't set in the nginx.conf

## Steps to reproduce

create a new container, work around the other two problems 😁

**Comment by frenck** [comment]
This issue I cannot reproduce since I run this on my personal production instance as well.
Could you provide your add-on configuration?

**Comment by hobbypunk90** [comment]
sure, sorry

```json
{
  "log_level": "info",
  "password": "password",
  "update_lists_on_start": false,
  "admin_port": 9200,
  "dns_port": 53,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "192.168.25.5",
  "ipv6_address": "",
  "virtual_host": "lamuella.galaxy",
  "hosts": [
     ...
  ]
}
```

**Comment by frenck** [comment]
Thanks! I'll will look into reproducing this one.

**Comment by frenck** [comment]
I was not able to reproduce this one. I've even tested changing ports around on SSL and non-SSL systems.

Tested on multiple systems, including:

- Vagrant based (Ubuntu 18.04) on latest Hassio/HomeAssistant.
- My production system (also Ubuntu 18.04).
- RaspberryPi running latest HassOS.

The functionality has already been part in previous releases as well.
