### ISSUE TITLE
Step 36-hosts.sh takes long time to run

### ISSUE THREAD

**Issue by brentil** [hassio-addons/addon-pi-hole#40]
# Problem/Motivation

> I enabled debug to test the dnsmasq user issue and while it was on exposed something about why my particular setup was taking a while to load.  I have 35 entries in my hosts config list for the addon and it takes on average 8 seconds for each entry to be added adding nearly 5 minutes to the startup of the PiHole addon.

## Expected behavior

> Hosts entries should be quick to add 

## Actual behavior

> Host entries take on average 8 seconds per host to add

## Steps to reproduce

> Enable debug and add a long list of hosts and watch the logs during startup.

## Hardware & Software

- RasPi3, 
- HA 0.76.2
- SU 127
- HassIO 1.9
- Arch Linux aarch64
- Pi-Hole addon 1.3.0 and 2.0.2

## Proposed changes

> Maybe instead of iterating over the list one entry at a time inject the entire list at once?

**Comment by frenck** [comment]
I agree this is an issue which needs to be addressed. 
Thank you for reporting this.

**Comment by frenck** [comment]
Not stale, thanks bot 👍
