### ISSUE TITLE
!secret support for password

### ISSUE THREAD

**Issue by ScholliYT** [hassio-addons/addon-pi-hole#42]
# Problem/Motivation
documentation says !secret is supported. But when I start the addon I get this in the log: 
```
ERROR: This add-on does not support secrets!
FATAL: You need to set a password!
```

## Expected behavior

> the addon loads the password from the secrets.yaml file

## Actual behavior

> the addon throws an error in the log.

## Steps to reproduce

> paste this line in the addon configuration: `"password": "!secret pihole_password",`

Addon version: 2.0.2

**Comment by tjorim** [comment]
Thanks for reporting the issue, it's probably a simple fix (#43).
The main dev of these add-ons is currently on holiday,
but will take a look when he can.

**Comment by ScholliYT** [comment]
thanks for the quick fix :) 

Can you help me applying this? where do can I find this file in my hassio installation?

**Comment by frenck** [comment]
Thanks for fixing this @tjorim  👍

**Comment by tjorim** [comment]
This can't be (easily) fixed on a hassio install (as far as I know).
New release should be up in an hour or so, @ScholliYT, update and it should be fine.
As soon as it's published, go to the 'Add-on Store' and click the little refresh button in the top right. Then you should see an update for the add-on.

**Comment by frenck** [comment]
@tjorim A merge does not trigger a release... so no, there is no new release in an hour or so...
I hope I will be able to create a release this week.

**Comment by tjorim** [comment]
Oh, thought your super advanced automations took care of all this 😆
