### ISSUE TITLE
Add securing techniques to documentation

### ISSUE THREAD

**Issue by dale3h** [hassio-addons/addon-pi-hole#46]
# Problem/Motivation

Too many people are asking for help with simple errors such as:

- `FATAL: Please choose a different password, this one is unsafe!`
- `FATAL: The configured certfile is not found`

## Expected behavior

If someone follows the steps in the [Installation][installation] section of the documentation, they should know that a secure password and setting up an SSL certificate are required by default.

## Actual behavior

People are often confused by errors because they followed the current [installation] steps properly.

## Steps to reproduce

Follow the steps found in the current [installation] section of the documentation.

## Proposed changes

1. Add a step explaining to set a secure password.
1. Add a step explaining that SSL certificates need to be generated, otherwise SSL needs to be set to false.

[installation]: https://github.com/hassio-addons/addon-pi-hole#installation

**Comment by ludeeus** [comment]
How about adding a step after install with this:
> 3. Configure this add-on, look at example and configuration options below.
