### ISSUE TITLE
No Web UI 

### ISSUE THREAD

**Issue by mpgoebel** [hassio-addons/addon-pi-hole#5]
With the following options 
```
{
  "log_level": "trace",
  "password": "",
  "update_lists_on_start": true,
  "web_port": 80,
  "dns_port": 53,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "",
  "ipv6_address": "",
  "virtual_host": "nottelling.duckdns.org"
}
```

I have added the iframe panel and the pi hole sensors, I was able to see the sensors register something other than unavailable (zeros except the last sensor for blocked domains) but I have never been able to see the web ui.  The following log is left when everything is loaded.  I have port forwarding on for port 80 to port 80 on my hassio instance, not sure if that is necessary.

```
  "version": "1.1",
  "last_version": "1.1",
  "features": [
    "shutdown",
    "reboot",
    "update",
    "hostname"
  ],
  "hostname": "hassio",
  "os": "GNU/Linux"
} .hostname
[cont-init.d] 15-hostname.sh: exited 0.
[cont-init.d] 16-logfiles.sh: executing... 
TRACE: hass.file_exists: /data/log/pihole.log
TRACE: hass.file_exists: /data/log/pihole-FTL.log
[cont-init.d] 16-logfiles.sh: exited 0.
[cont-init.d] 50-gravity.sh: executing... 
TRACE: hass.config.true: update_lists_on_start
TRACE: hass.jq.is_boolean: /data/options.json .update_lists_on_start
TRACE: hass.jq.is: /data/options.json .update_lists_on_start boolean
TRACE: hass.jq: /data/options.json .update_lists_on_start | if type=="boolean" then true else false end
TRACE: hass.config.get: update_lists_on_start
TRACE: hass.config.exists: update_lists_on_start
TRACE: hass.jq.exists: /data/options.json .update_lists_on_start
TRACE: hass.jq: /data/options.json .update_lists_on_start
TRACE: hass.jq.is_string: /data/options.json .update_lists_on_start
TRACE: hass.jq.is: /data/options.json .update_lists_on_start string
TRACE: hass.jq: /data/options.json .update_lists_on_start | if type=="string" then true else false end
TRACE: hass.jq.is_boolean: /data/options.json .update_lists_on_start
TRACE: hass.jq.is: /data/options.json .update_lists_on_start boolean
TRACE: hass.jq: /data/options.json .update_lists_on_start | if type=="boolean" then true else false end
TRACE: hass.jq: /data/options.json .update_lists_on_start // false
DEBUG: Generating block lists
:::
::: Neutrino emissions detected...
:::
::: Pulling source lists into range... done!
:::
::: Getting raw.githubusercontent.com list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting sysctl.org list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting zeustracker.abuse.ch list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting hosts-file.net list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: 
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 129942 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 106698 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 6 domains... done!
::: Nothing to blacklist!
::: No wildcards used!
::: Formatting domains into a HOSTS file...::: Nothing to blacklist!
 done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq...s6 service not found for dnsmasq, exiting...
 done!
::: DNS service is running
::: Pi-hole blocking is Enabled
[cont-init.d] 50-gravity.sh: exited 0.
[cont-init.d] 99-tests.sh: executing... 
DEBUG: Testing if all configurations valid
dnsmasq: syntax check OK.
[15-Nov-2017 15:07:35] NOTICE: configuration file /etc/php7/php-fpm.conf test is successful
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
[cont-init.d] 99-tests.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
starting version 3.2.2
[services.d] done.
dnsmasq: started, version 2.76 cachesize 10000
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: read /etc/hosts - 8 addresses
dnsmasq: read /etc/pihole/black.list - 0 addresses
dnsmasq: read /etc/pihole/local.list - 2 addresses
dnsmasq: read /etc/pihole/gravity.list - 106698 addresses
```

**Comment by frenck** [comment]
@mpgoebel Have you tried `http://<ip of your device running hassio>/admin/index.php` ?

**Comment by mpgoebel** [comment]
I did try it both with my local ip and my external duckdns ip with both http and https, https shows error 404, http just timed out.

Matt Goebel
316-680-8442
On Nov 15, 2017 3:31 PM, Franck Nijhof <notifications@github.com> wrote:

@mpgoebel<https://github.com/mpgoebel> Have you tried http://<ip of your device running hassio>/admin/index.php ?

**Comment by frenck** [comment]
Ok, that is odd, since 404's should not be served. It there something else serving maybe?

Some options:
- Try changing the web port to something different and try accessing it on the internal IP address.
- You are running a generic Linux installation of Hass.io. Ensure the correct interface is selected by the add-on (see debug information) or try to set it manually in the add-on configuration.

**Comment by mpgoebel** [comment]
I changed the web port to 85 and it worked on my internal ip but not my external IP, also it looks like the open web UI button only opens in port 80 instead of what was specified in the web port code.

Matt Goebel
316-680-8442
On Nov 15, 2017 3:41 PM, Franck Nijhof <notifications@github.com> wrote:

Ok, that is odd, since 404's should not be served. It there something else serving maybe?

Some options:

  *   Try changing the web port to something different and try accessing it on the internal IP address.
  *   You are running a generic Linux installation of Hass.io. Ensure the correct interface is selected by the add-on (see debug information) or try to set it manually in the add-on configuration.

**Comment by mpgoebel** [comment]
Two things, I found that the let's encrypt add on occupies port 80 and I forwarded port 85 on my router but i get a"failed host check (external IP vs internal ip) when trying to access the web UI with my external IP:85.

**Comment by frenck** [comment]
@mpgoebel The failed host check is related to #6.
The working of the WebUI button is confirmed, but the issue is unsolvable due to a limitation of Hass.io. Port numbers for add-ons running on a host network level can't be picked up by the UI.

**Comment by mpgoebel** [comment]
The update fixed the open UI issue but i still am not able to see it as an iframe in the frontend

**Comment by frenck** [comment]
That is probably releated to #10, which will be fixed soon.

**Comment by mpgoebel** [comment]
Only other thing I saw that is odd is that I have not blocked any ads whatsoever since installing pi hole.  Just lucky or is something setup incorrectly?

**Comment by frenck** [comment]
Did you point your devices to it? Does it actually filter?

**Comment by mdopp** [comment]
@mpgoebel Did it ever work with your router and port 80? Which router do you use? I used to have problems with my FritzBox, as it was not forwarding port 80, even if it was configured.

**Comment by mpgoebel** [comment]
@mdopp I have forwarding setup for port 80.  I use a unifi security gateway and controller for my networking at home.  I just have 80 to 80 on my Pi's address.

**Comment by frenck** [comment]
@mpgoebel This is one method:
https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245

**Comment by frenck** [comment]
This is becoming a support and/or chat issue.
I like to keep the GitHub project about true issues with the code base.

Could you guys please refer to the Home Assistant forum or chat for general support questions? That would be awesome.

**Comment by Makr91** [comment]
Try adding the domain you have your SSL for here: "ipv4_address": "pi.example.com",

**Comment by frenck** [comment]
Please ignore that advise of @Makr91. While it is a valid workaround, it will cause other issues in the long run. The issue at hand is current in issue #10  and will be fixed soon.

**Comment by frenck** [comment]
Locking down this issue. This is not a forum.
