### ISSUE TITLE
Update documentation to specify the step of setting up DNS address in router settings

### ISSUE THREAD

**Issue by slonkar** [hassio-addons/addon-pi-hole#50]
# Problem/Motivation

After going through pi-hole add on installation, on web interface I was not seeing any information about total queries, queries blocked etc. as I have not configured my DNS address in router settings.

## Expected behavior

In installation guide, we could have extra line/note to make sure that users don't forget to set it up.

## Actual behavior

N/A

## Steps to reproduce

1. Install add-on on hassio.
2. Go to pi-hole web interface.
3. Observe dashboard data.

## Proposed changes

Add extra step to installation guide to configure DNS address correctly.

**Comment by slonkar** [comment]
Feel free to assign it to me if you guys think this is a valid request. I will submit the PR.

**Comment by slonkar** [comment]
@frenck What's the recommendation for the set up?

**Comment by frenck** [comment]
@slonkar There is not a recommended method, that is kinda the issue.
You could do a manual setup in your system (override network setting), forward requests from your router, change the DNS settings in your current DHCP system, use Pi-hole as the DNS server and even other setups are possible.

**Comment by inverse** [comment]
Would linking to this provide insight? https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245 

Is this still the most up to date guide?

**Comment by frenck** [comment]
That is a nice idea, but even that page is not complete.

**Comment by frenck** [comment]
Closing this issue, since I have no clue on where to start with this.
People should be aware / learn what they are doing, this is not something you can just write up as a simple tutorial.
