### ISSUE TITLE
dnsmasq: failed to create listening socket for Address in use

### ISSUE THREAD

**Issue by jmtatsch** [hassio-addons/addon-pi-hole#54]
# Problem/Motivation

dnsmasq: failed to create listening socket for Address in use

## Expected behavior

dnsmasq getting its desired port

## Actual behavior

a lot of attempts to get the port

## Steps to reproduce

Install current Ubuntu 1804 with Hassio, install pi hole add-on 

## Proposed changes

Monitor the failed attempts in the log and augment the log with a hint for the user
Please check if the DNS port on your host machine are already in use by another process with: sudo lsof -i | grep "domain"                                                                                                                                                                    
For Ubuntu 18.04 consider disabling the DNSStubListener in /etc/systemd/resolved.conf on your host. system

**Comment by frenck** [comment]
👍 @d0ugal
