### ISSUE TITLE
Logs not properly being flushed

### ISSUE THREAD

**Issue by DigitalRogues** [hassio-addons/addon-pi-hole#56]
# Problem/Motivation

running the flush logs script in the UI, does not actually clear out the database, and the log rotate may not be happening either.

## Expected behavior

when clicking the flush logs, I expect the graphs to clear the data.

## Actual behavior

the data is still in the graphs.

## Steps to reproduce

using docker exec into the running container and running `pihole -f` shows this output
    
    [i] Flushing /var/log/pihole.log ...error: Ignoring /etc/logrotate.d/pihole because it is writable by group or others.

    error: Ignoring /etc/logrotate.d/pihole because it is writable by group or others.

    /opt/pihole/piholeLogFlush.sh: line 59: sqlite3: command not found

    [✓] Flushed /var/log/pihole.log

    [✓] Deleted  queries from database

## Proposed changes

in the container /etc/logrotate.d/pihole original permissions were

    -rw-rw-rw- 1 root root  208 Jun 15  2018 pihole

 I was able to fix the log rotate issue by running, 

    chmod 644 /etc/logrotate.d/pihole 

In the v2.1.0 repo tag the file shows the proper file permissions, `-rw-r--r--` I've dug around, but I couldn't find where it's getting changed or where to change it in the install/docker process. 

and to install sqlite, sqlite-3.24.0-r0 is the version it installed
 
    apk --no-cache add sqlite

I'm assuming that would just get added to the docker file in the normal app install process.

After those tweaks running `pinhole -f` shows data being removed from the `/etc/pihole/pihole-FTL.db` file.

**Comment by jacoknapp** [comment]
Thank you @DigitalRogues for taking the time to do a deep dive on this issue. I was able to clear up about 45% of  my hassio hard drive with the above advice. and drop the memory consumption by 10-15%. This is actually a pretty large issue for anyone running the plugin over a longer period of time, because it causes a data leak without an easy way for anyone to clear it up.

**Comment by sermayoral** [comment]
Same problem.

Is anyone trying to solve it?

Regards :-)

**Comment by jacoknapp** [comment]
Bump, because it’s still a problem.

**Comment by alex3305** [comment]
Same issue here. Log is about 1GB at the moment. I've set up the fix by @DigitalRogues and am testing it now. Will report back whether or not this issue has resolved.

**Comment by alex3305** [comment]
Bump. This is still an issue.

**Comment by jacoknapp** [comment]
Still an issue, bump

Jacob Knapp

**Comment by frenck** [comment]
Issue has been fixed an adressed in the current dev version of the add-on.
