### ISSUE TITLE
Reverse Proxy and Pi Hole in iframe

### ISSUE THREAD

**Issue by talondnb** [hassio-addons/addon-pi-hole#59]
# Problem/Motivation

> Issue when using reverse proxy with pi-hole

## Expected behavior

> using with an iframe, nginx reverse proxy configured. pi hole should load within an iframe with this configuration as other hosted applications.

## Actual behavior

> with reverse proxy configuration proxy pass pointing to LAN address, pihole still seems to push my DNS url instead and so does not load.

## Steps to reproduce

> NGINX reverse proxy addon with the following configuration:

```
nginx_proxy_default.conf:

location /pihole/ {
    rewrite /pihole/(.*) /$1 break;
    proxy_pass http://192.168.0.200:4865/admin;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}

panel_iframe:
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: https://xxxx.duckdns.org/pihole

```

## Proposed changes

> is this the behaviour of the addon itself? no other addons exhibit this behaviour so assuming pi hole issue at this point.

**Comment by frenck** [comment]
This is behavior by pi-hole itself and not by the add-on.
