### ISSUE TITLE
Not using virtual host

### ISSUE THREAD

**Issue by CountParadox** [hassio-addons/addon-pi-hole#6]
# Problem/Motivation

My install of Pi-Hole does not seem to be accepting my duckdns.org URL in the virtual host config.

## Expected behavior

I would expect to be able to access the admin panel at https://mydomain.duckdns.org:8080/admin/index.php

## Actual behavior

I get the following error:

`Failed Host Check: mydomain.duckdns.org vs 172.16.0.xx, , hassio.local, pi.hole, localhost, hassio, hassio.local
`

It appears to be not adding my domain to whitelist of hostnames it can be accessed on.

## Steps to reproduce

Based on the lack of other reports, it would seem this may be specific to mine.
I can provide access to logs etc as required.

## Additional Info

I have tried saving the config again, restarting several times, restarting hassio also. Doesn't seem to take effect. The config in hassio shows the domain, as well as my other customised items in the config do work, just this domain part.

I am able to access the admin UI perfectly fine via https://localip:8080/admin/index.php but I would prefer domain due to the certificate

My config is:

`{
  "log_level": "info",
  "password": "mypassword",
  "update_lists_on_start": true,
  "web_port": 8080,
  "dns_port": 53,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "",
  "ipv6_address": "",
  "virtual_host": "mydomain.duckdns.org"
}`

**Comment by mpgoebel** [comment]
I am encountering this bug as well

**Comment by frenck** [comment]
Fixed in `master` branch, will be included in next release.
