### ISSUE TITLE
Add support for Unbound recursive DNS resolver

### ISSUE THREAD

**Issue by chriscrowe** [hassio-addons/addon-pi-hole#66]
# Problem/Motivation

> Would be nice to have an option for a private resolver instead of using 3rd parties (mostly for privacy).

## Proposed changes

> Adding unbound package to installer and config file recommended by Pi-hole [here](https://docs.pi-hole.net/guides/unbound/)

**Comment by frenck** [comment]
Closing request, see #67 for reasoning.
