### ISSUE TITLE
Support for DNS over HTTPs

### ISSUE THREAD

**Issue by else** [hassio-addons/addon-pi-hole#70]
# Problem/Motivation

Many internet providers spy on their user's DNS queries to gather analytics. A possible countermeasure can be to make use of DNS over HTTPs. It'd be great this add-on could support this out of the box, since a custom image is anyhow built.

See [official guide](https://docs.pi-hole.net/guides/dns-over-https/) over at pi-hole docs for one possible solution. It'd be great if the upstream DNS could be configurable though.

## Proposed changes

Add support for DNS over HTTPs out of the box, ideally configurable (toggleable).

**Comment by shanefreeman** [comment]
I second this

**Comment by frenck** [comment]
Well.. The funny thing is: Pi-hole does not support DoH.
They write they do: but then they write about installing cloudflared and change the upstream of Pi-hole to it... 🤷‍♂ 

Cloudflared should be a separate add-on in the Hass.io/Docker world and not part of this add-on.

Hence, I'm going to close this request.
