### ISSUE TITLE
PiHole broken after upgrading to 3.0.1

### ISSUE THREAD

**Issue by RualdOrdelman** [hassio-addons/addon-pi-hole#71]
# Problem/Motivation

After updating to PiHole Addon 3.0.1 my PiHole won't start. No error in the log with loglevel info, debug or trace

## Expected behavior

Container starts as usual 

## Actual behavior

Container stopped and PiHole is offline. So this is critical. 

## Steps to reproduce

Got an 2.x PiHole Addon, upgrade to 3.0.1 and start the PiHole Addon. 

## Current config
`
{
  "log_level": "debug",
  "password": "*******",
  "update_lists_on_start": true,
  "admin_port": 4865,
  "dns_port": 53,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "interface": "",
  "ipv6": true,
  "ipv4_address": "",
  "ipv6_address": "",
  "virtual_host": "thuis.banaan.nl",
  "hosts": []
}
`
## Log output
[pihole.txt](https://github.com/hassio-addons/addon-pi-hole/files/2975675/pihole.txt)

**Comment by frenck** [comment]
Please provide logs! @RualdOrdelman

**Comment by RualdOrdelman** [comment]
I've provide the log as a URL below in my post.
See: https://github.com/hassio-addons/addon-pi-hole/files/2975675/pihole.txt

**Comment by frenck** [comment]
Sorry @RualdOrdelman Missed that,... looking into it right away

**Comment by RualdOrdelman** [comment]
Thanks. Tell me if I can help you by providing more information or something.

**Comment by Joeboyc2** [comment]
Same issue here, its knocked my whole network offline because pi hole runs my dhcp :(

Trying to restore from backup but failing

**Comment by frenck** [comment]
Found it, will bring up a patch in a second...

**Comment by frenck** [comment]
Just release v3.0.2 which addresses this issues.
