### ISSUE TITLE
Admin Interface Port Auto Redirect

### ISSUE THREAD

**Issue by xNuno** [hassio-addons/addon-pi-hole#73]
# Problem/Motivation

When open the admin panel using reverse proxy it always tries to change the address from https://piholeadmin.duckdns.org/admin/ to https://piholeadmin.duckdns.org:4865/admin ... If I use other application like grafana it works like charm without always redirecting to app port number.

## Expected behavior

Open pihole address running on port 4865 but without forcing the url redirection.

## Actual behavior

Url gets redirect all the time to include the port number. This is the job for the reverse proxy, no need to be forced by pihole.

## Steps to reproduce

Setup DuckDns to point your routers internet IP
Setup reverse proxy to look to duckdns URL alias
Open URL without port number using https

## Proposed changes

Disable the auto url redirection to include the port number.

More info: https://github.com/pi-hole/docker-pi-hole/issues/430

**Comment by frenck** [comment]
I wish I could help you there m8.

This add-on wraps Pi-hole and has some modifications to make it work in Alpine Linux and let it play nicely with Hass.io/Home Assistant.

I get that they redirect you to here, nevertheless, this is not a fork of Pi-hole, nor are there any of their sources in here.

Nevertheless, I'll look into it, see if I can find this piece of brain damage.

PS: If you are just looking for ad blocking, there is also an AdGuard Home add-on available, which, IMHO, is saner...

**Comment by frenck** [comment]
@xNuno Can you share me your reverse proxy setup and config so I have a reproduction config?
