### ISSUE TITLE
adding hostrecord to web interface

### ISSUE THREAD

**Issue by lildevilx** [hassio-addons/addon-pi-hole#74]
previously when i was running hassbian + pihole i was able to create my own hostrecord by running `sudo pihole -a hostrecord example.com 192.168.0.12`
but i have since moved over to hassio  opting for more of its features. but one of the thing i'm missing out on the pihole now is adding hostrecord that allows me to redirect certain websites to  a local ip. is there anyway this can be added to the webui?

**Comment by frenck** [comment]
See: <https://github.com/hassio-addons/addon-pi-hole#option-hosts>

Example: <https://github.com/hassio-addons/addon-pi-hole#configuration>
