### ISSUE TITLE
Hassio DNS issues

### ISSUE THREAD

**Issue by carloscae** [hassio-addons/addon-pi-hole#75]
# Problem/Motivation

> Hassio stops working properly after a couple of days with Pi-Hole installed and working. Multiple platforms (Arlo, Logi-Circle, Alexa-Media, etc) even weather icon from yr will fail to load.

## Steps to reproduce

> Running Hassio on Virtualbox with Static IP
> Set Pi-Hole as DNS server on Router
> Works fine for a day or two, then platforms starts to fail to update, and if you restart Hassio it will fail to load at all. (Maybe a DNS Cache issue?)

## Proposed changes

> Have an option to forward all Hassio requests to DNS resolver instead of Pi-Hole

**Comment by frenck** [comment]
@carloscae You need to set a static DNS external DNS on your main machine as well (or else it will become a client of itself).

**Comment by carloscae** [comment]
@frenck the external machine as also static IP and DNS.

**Comment by frenck** [comment]
EXTERNAL static DNS?

**Comment by carloscae** [comment]
Sorry, so this machine needs to have a DNS that bypasses router and Pi-Hole?

**Comment by frenck** [comment]
Yes, or else it will become a client of itself.

**Comment by carloscae** [comment]
I will try again and post back here if issues return. Thanks for the clarification.
