### ISSUE TITLE
login in iframe not working

### ISSUE THREAD

**Issue by Kugelfang666** [hassio-addons/addon-pi-hole#76]
# Problem/Motivation

cannot login when accessing the guide via HASSIO (panel_iframe)
## Expected behavior

> (What you expected to happen)

login and manage settings

> (What actually happened)

nothing

> (How can someone else make/see it happen)

install pi-hole Addon and access is via a panel on HASSIO

if one accesses pi-hole directly via the bowser everything works

**Comment by Jeltel** [comment]
It works here. I have this to include the panel:
```  pihole:
    title: 'PiHole'
    url: 'https://192.168.1.37:4865'
    icon: mdi:pi-hole
```
