### ISSUE TITLE
Ingress compatibility

### ISSUE THREAD

**Issue by Brausmith** [hassio-addons/addon-pi-hole#77]
# Problem/Motivation
With HA 0.92 receiving the Ingress implementation, it would awesome for the Pi-Hole add-on to support it.

**Comment by frenck** [comment]
This needs to be tested, but given the admin panel is based on PHP (and my previous experiences with getting a PHP app to work with Ingress), I don't think this will happen.

If you want an alternative, that does support Ingress, I would recommend AdGuard Home (also available on the community add-ons repository).

**Comment by iautom8things** [comment]
> ... given the admin panel is based on PHP (and my previous experiences with getting a PHP app to work with Ingress), I don't think this will happen.

What about PHP made this difficult?  I've worked with PHP, just curious if this is something I might be able to help out with.

**Comment by frenck** [comment]
@iautom8things I've been a DevOps engineer and a PHP programmer since 1998. I'm certified as well. I'm perfectly capable of configuring a PHP server and (if needed) modifying a PHP code base.

Thanks for your offer.

**Comment by iautom8things** [comment]
Didn't realize this was a pissing contest.  Good luck!

**Comment by frenck** [comment]
Uuhu are you OK @iautom8things?
I did not find it offensive or didn't mean to step on your toes there m8...

My thanks, in the end, was polite and sincere.

**Comment by iautom8things** [comment]
I was genuinely curious about what made this task so difficult as you described.  If you can't tell that your response was dismissive then I won't try to help you see it.

I'll see myself out, though 👋

**Comment by frenck** [comment]
😳 ok, that’s fine.

🤷‍♂️

**Comment by ralphhughes** [comment]
+1 I would also like to see ingress functionality
