### ISSUE TITLE
Local host  names not showing (only IP showing)

### ISSUE THREAD

**Issue by ministryofsillywalks** [hassio-addons/addon-pi-hole#78]
On the dashboard in the Top Client list only the IP addresses are shown and not the names associated with the device.
I tried added the hosts manually to the config to resolve the names however it still doesn't work.
I'm not sure this is an issue with Pi-Hole or my router (Fritzbox) not forwarding the correct information.

Currently my setup is:
Fritzbox as DHCP server
Pihole set as local DNS server
Fritzbox set as custom DNS server inside Pihole 
OpenDNS set as external DNS server inside Fritzbox

Fritzbox shows the names of the clients just fine
![image](https://user-images.githubusercontent.com/10544895/57013600-8f3c1e80-6c0c-11e9-907e-d610ea86c7b7.png)

However inside Pihole I only see the IP addresses
![image](https://user-images.githubusercontent.com/10544895/57013614-a67b0c00-6c0c-11e9-82cf-98ae8202e63b.png)

Inside the hassio pihole conf I set up hosts but this didn't do anything:
![image](https://user-images.githubusercontent.com/10544895/57013634-c3afda80-6c0c-11e9-9ae0-3c5f8ee8c71d.png)

I read some info saying I should setup the hosts manually inside /etc/hosts for pihole however my understanding is that setting the hosts in the conf does this. Also I'm not sure how to access piholes hosts file.

Any input apreciated.

**Comment by ajdezigns** [comment]
I'm having the same issue

**Comment by Jeltel** [comment]
I'm also not getting this to work. With pretty much the same setup.

Also tried to use Use Conditional Forwarding on the DNS page in the settings. This worked when running PiHole in a docker on a Synology NAS.

**Comment by wildoracle** [comment]
I'm having exactly the same problem, with AsusWRT-merlin firmware router. I tried editing the hosts file inside of the configurator editor, but it reverts back to its previous state when I reboot. I might try SSH to edit the hosts file and chron -x it.
