### ISSUE TITLE
Request: Allow the DHCP function to be used.

### ISSUE THREAD

**Issue by mdehaas** [hassio-addons/addon-pi-hole#8]
# Problem/Motivation

> Allow the DHCP function in Pi-Hole to be used

## Expected behavior

> DHCP portion of Pi-Hole should report usage of DHCP addresses and computers should get an IP and report HassIO as the DHCP server

## Actual behavior

> No IP Addresses are being assigned and nothing is reported in the DHCP options

## Steps to reproduce

> Configure HassIO/Pi-Hole as the only DHCP server in the network

## Proposed changes

> I'm not a Docker expert (far from it) but I can search and I found the following GitHub repository which has DHCP server container which is also Alpine based. The dockerfile uses port 67 (TCP and UDP) which the listening port for DHCP requests. The TCP port should not be needed IMO.
https://github.com/jcbiellikltd/docker-dhcpd/blob/master/Dockerfile
Downside is that this may cause incompatibility with the DHCP Server addon.

**Comment by frenck** [comment]
I've just tested it again on a different test device to make sure it works, and it does.
My main installation also runs it that way (on my home network).

The add-on runs on the host network and therefore there is nothing to do with ports (secondly, you don't need to expose ports explicitly when using Hassio add-ons).

It is true that is causes incompatibility with the DHCP server add-on, which is expected in this case and not something I could do anything about. That is something the user has to arrange.
