### ISSUE TITLE
Virtual Host not working on port's other than 8123

### ISSUE THREAD

**Issue by ajdezigns** [hassio-addons/addon-pi-hole#85]
# Problem/Motivation

When going to https://****duckdns.org:8123 all is good but when going to https://****duckdns.org:4865 or another port to my pi's domain I get this error on chrome

> This site can’t be reached zeak.duckdns.org refused to connect.
> Try:
> 
> Checking the connection
> Checking the proxy and the firewall
> ERR_CONNECTION_REFUSED

Additionally, under the Hosts section, I have this code:
```
  "hosts": [
    {
      "name": "laundrycam",
      "ip": "192.168.0.94"
    }
```
and it does nothing same error as above.

## Expected behavior

The expected behavior is that the urls would resolve to the correct ip's

## Actual behavior

errors out

## Steps to reproduce

n/a

## Proposed changes

I have no idea the only workaround I've been able to use the direct IP addresses.

**Comment by ajdezigns** [comment]
Looks like this issue goes back 2 years https://github.com/hassio-addons/addon-pi-hole/issues/6

**Comment by kreisklasse** [comment]
I have the same failure output as in #6
i try to access my pi2-Hassio via zerotier.
Access via zerotier to HA via port 8123 works perfect, but to the pihole-port 4865 it shows this

`Failed Host Check: 192.168.xx.xx vs 192.168.y.y, , hassio.local, pi.hole, localhost, hassio, hassio.local`

while 192.168.xx.xx is the zerotier ip and 192.168.y.y the local Hassio-IP

no further log entries at HassOS.


System:
RasPI2
HassOS 2.12
Hass.io supervisor 167
piHole-Addon 3.0.2
zerotier-Addon 0.3.0

**Comment by frenck** [comment]
Next version of the add-on uses Ingress, which makes this no longer an issue.
