### ISSUE TITLE
Pi Hole for resolving local domain names

### ISSUE THREAD

**Issue by rschuetzler** [hassio-addons/addon-pi-hole#9]
# Problem/Motivation

I’m currently using a local DNS to resolve a local hostname within my network. Is there a way I can get the same functionality in the pi-hole addon?

## Expected behavior

According to [this walkthrough](https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533), it seems like it would be possible if we could create our own `dnsmasq` conf file.

## Actual behavior

There is no current ability to create your own local DNS records

## Proposed changes

Add the capability to add our own custom DNS records to pi-hole, either through the configuration, or through editing config files directly.

**Comment by frenck** [comment]
Done, added it in v0.3.0, which was just released.
