### ISSUE TITLE
404 error in recent queries

### ISSUE THREAD

**Issue by bebach8** [hassio-addons/addon-pi-hole#92]
# Problem/Motivation

When in Pi Hole UI, in left menu you click "Network" and in clients list you click on device IP address to show recent queries by that device, it opens new browser tab and in that tab you get 404 error.

In new tab it opens it goes to address http://"hassio ip"/admin/queries.php?client="clicked device ip address" (without quotes) ex. 192.168.1.2

![problem](https://user-images.githubusercontent.com/7442779/64190498-d5cdae00-ce76-11e9-9182-ab4fb79222b0.jpg)

**Comment by sinclairpaul** [comment]
Can you confirm if this is via ingress or with the web interface exposed, its hard to tell from the screenshot.

**Comment by bebach8** [comment]
Ingres, sir. http://ip/a0d7b954_pi-hole

**Comment by sinclairpaul** [comment]
Can you retest when setting the network port for the UI and access via that.  It looks like a Javascript issue that the client reads the URL, will confirm later but if thats the case it is unlikely to be fixed for Ingress.

**Comment by bebach8** [comment]
Without ingress, port 12345

![without ingress](https://user-images.githubusercontent.com/7442779/64269429-2823d300-cf3a-11e9-8c5c-e3808697ad28.jpg)
![without ingress2](https://user-images.githubusercontent.com/7442779/64269437-2a862d00-cf3a-11e9-8bcc-d91c686d7147.jpg)

It says "File not found" error.

**Comment by sinclairpaul** [comment]
It is indeed a Javascript issue, https://github.com/pi-hole/AdminLTE/blob/44aff727e59d129e6201341caa1d74c8b2954bd2/scripts/pi-hole/js/network.js#L117

With Ingress the admin interface was moved down a level, so the admin folder does not exist.  May be able to fix this under the exposed addon, but unlikely under Ingress.  For the time being you can load the page on the exposed addon by removing the /admin/ from the URI.
