### ISSUE TITLE
uninstall leaves ubuntu 18.04 host system without workable dns resolver

### ISSUE THREAD

**Issue by increddibelly** [hassio-addons/addon-pi-hole#94]
I've had some intermittent internet connectivity which I've pinpointed to my DNS resolver. My PiHole is running on an old Atom D525 system (running ubuntu 18.04), which I suspect is simply not strong enough to do all the things I tell it to do.

I wanted to try un- and reinstall the pi-Hole addon for troubleshooting. 
Uninstall took the addon away neatly and removed the docker container, but now I have a nasty bunch of networking problems on my hassio host.
- install button of pihole (and other addons) turns red after a few seconds; this boils down to being unable to resolve Github.com. 
- ubuntu thinks it's offline: it can't resolve DNS queries.
- I can no longer change network settings for my ethernet / wifi adapters; the settings screen simply does not come up. I wish I'd be able to read some logs for this, it might be a big clue as to what's happening.
- desperately changing DNS servers in all the dnsmasq / resolved.conf / netplan files and following every guide available on the internet does not _resolve_ anything. (excuse the horrid puns).

steps to reproduce:
- give hassio box static ip
- set hassio box dns to 127.0.0.1 and 8.8.8.8 (*)
- install pi-hole addon from hassio add on store. 
- enjoy ad free life.
- uninstall pi-hole addon from hassio add on page. 
- hassio box can no longer resolve dns queries

(*) (removing 127.0.0.1 does nothing, surprisingly / unfortunately)

QFT: 
_Originally posted by @vermi5 in https://github.com/hassio-addons/addon-pi-hole/issues/35#issuecomment-416322228_
What I can't fathom is the incredible mess of a host system I must have so that if I try to uninstall the addon, Ubuntu cannot resolve URLs anymore (the homeassistant container still can resolve but If I press Install or update buttons on the frontend they do nothing) so I can't use the reinstall workaround.

**Comment by increddibelly** [comment]
I will post Network Manager logs when I get home and if I can find them. should `journalctl -u NetworkManager` do that trick?

**Comment by sinclairpaul** [comment]
The documentation for the addon states that you need to give your host operating system a static IP and static external DNS server.  This isn't an issue with the addon so I am closing.  I would suggest to jump on Discord if you need some assistance resolving your system issues.
