### ISSUE TITLE
Network overview: click on ip of a client opens a new window with a wrong url

### ISSUE THREAD

**Issue by deluxestyle** [hassio-addons/addon-pi-hole#96]
# Problem/Motivation

> wrong url in a new tap when I click on a client ip within the network section of pi hole
https://hass.io:8123/admin/queries.php?client=192.168.200.27

## Expected behavior

> it should open in the same tab within the pi hole interface the query log section with filter on the clicked ip

**Comment by sinclairpaul** [comment]
Duplicate of #92
